# Generated by Django 4.2 on 2023-04-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
